package io.petstore.test.oas.assertions;

import io.petstore.test.oas.client.model.Order;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link Order.StatusEnum.Adapter} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractOrderStatusEnumAdapterAssert<S extends AbstractOrderStatusEnumAdapterAssert<S, A>, A extends Order.StatusEnum.Adapter> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractOrderStatusEnumAdapterAssert}</code> to make assertions on actual Order.StatusEnum.Adapter.
   * @param actual the Order.StatusEnum.Adapter we want to make assertions on.
   */
  protected AbstractOrderStatusEnumAdapterAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
