package io.petstore.test.oas.assertions;

import io.petstore.test.oas.client.model.Pet;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link Pet.StatusEnum.Adapter} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractPetStatusEnumAdapterAssert<S extends AbstractPetStatusEnumAdapterAssert<S, A>, A extends Pet.StatusEnum.Adapter> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractPetStatusEnumAdapterAssert}</code> to make assertions on actual Pet.StatusEnum.Adapter.
   * @param actual the Pet.StatusEnum.Adapter we want to make assertions on.
   */
  protected AbstractPetStatusEnumAdapterAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
