package io.petstore.test.oas.assertions;

import io.petstore.test.oas.client.model.ModelApiResponse;

/**
 * {@link ModelApiResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractModelApiResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ModelApiResponseAssert extends AbstractModelApiResponseAssert<ModelApiResponseAssert, ModelApiResponse> {

  /**
   * Creates a new <code>{@link ModelApiResponseAssert}</code> to make assertions on actual ModelApiResponse.
   * @param actual the ModelApiResponse we want to make assertions on.
   */
  public ModelApiResponseAssert(ModelApiResponse actual) {
    super(actual, ModelApiResponseAssert.class);
  }

  /**
   * An entry point for ModelApiResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myModelApiResponse)</code> and get specific assertion with code completion.
   * @param actual the ModelApiResponse we want to make assertions on.
   * @return a new <code>{@link ModelApiResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ModelApiResponseAssert assertThat(ModelApiResponse actual) {
    return new ModelApiResponseAssert(actual);
  }
}
