package io.petstore.test.oas.assertions;

import io.petstore.test.oas.client.model.Order;

/**
 * {@link Order} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractOrderAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class OrderAssert extends AbstractOrderAssert<OrderAssert, Order> {

  /**
   * Creates a new <code>{@link OrderAssert}</code> to make assertions on actual Order.
   * @param actual the Order we want to make assertions on.
   */
  public OrderAssert(Order actual) {
    super(actual, OrderAssert.class);
  }

  /**
   * An entry point for OrderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myOrder)</code> and get specific assertion with code completion.
   * @param actual the Order we want to make assertions on.
   * @return a new <code>{@link OrderAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static OrderAssert assertThat(Order actual) {
    return new OrderAssert(actual);
  }
}
