package io.petstore.test.oas.assertions;

import io.petstore.test.oas.client.model.Order;

/**
 * {@link Order.StatusEnum.Adapter} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractOrderStatusEnumAdapterAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class OrderStatusEnumAdapterAssert extends AbstractOrderStatusEnumAdapterAssert<OrderStatusEnumAdapterAssert, Order.StatusEnum.Adapter> {

  /**
   * Creates a new <code>{@link OrderStatusEnumAdapterAssert}</code> to make assertions on actual Order.StatusEnum.Adapter.
   * @param actual the Order.StatusEnum.Adapter we want to make assertions on.
   */
  public OrderStatusEnumAdapterAssert(Order.StatusEnum.Adapter actual) {
    super(actual, OrderStatusEnumAdapterAssert.class);
  }

  /**
   * An entry point for OrderStatusEnumAdapterAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myOrder.StatusEnum.Adapter)</code> and get specific assertion with code completion.
   * @param actual the Order.StatusEnum.Adapter we want to make assertions on.
   * @return a new <code>{@link OrderStatusEnumAdapterAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static OrderStatusEnumAdapterAssert assertThat(Order.StatusEnum.Adapter actual) {
    return new OrderStatusEnumAdapterAssert(actual);
  }
}
