package io.petstore.test.oas.assertions;

import io.petstore.test.oas.client.model.Pet;

/**
 * {@link Pet.StatusEnum} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPetStatusEnumAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class PetStatusEnumAssert extends AbstractPetStatusEnumAssert<PetStatusEnumAssert, Pet.StatusEnum> {

  /**
   * Creates a new <code>{@link PetStatusEnumAssert}</code> to make assertions on actual Pet.StatusEnum.
   * @param actual the Pet.StatusEnum we want to make assertions on.
   */
  public PetStatusEnumAssert(Pet.StatusEnum actual) {
    super(actual, PetStatusEnumAssert.class);
  }

  /**
   * An entry point for PetStatusEnumAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPet.StatusEnum)</code> and get specific assertion with code completion.
   * @param actual the Pet.StatusEnum we want to make assertions on.
   * @return a new <code>{@link PetStatusEnumAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PetStatusEnumAssert assertThat(Pet.StatusEnum actual) {
    return new PetStatusEnumAssert(actual);
  }
}
